### ISSUE TITLE
Task #3 Deployment help

### ISSUE THREAD

**Issue by reischlb** [IntegrOwlDiff/owl-diff-engine#3]
Help deployment with Docker, Vagrant, or some other tool.

**Comment by reischlb** [comment]
I have a question:

I don't really understand the method getService [Engine](https://github.com/IntegrOwlDiff/owl-diff-engine/blob/master/src/main/java/org/protege/owl/diff/Engine.java) class. Why are we sure that it will give a Service back?

**Comment by BenjaminBako** [comment]
I found this stackoverflow question to you.

http://stackoverflow.com/questions/450807/how-do-i-make-the-method-return-type-generic
